@startuml

!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Context.puml

LAYOUT_WITH_LEGEND()


Person(callCenterManager, "Менеджер кол-центра", "Обрабатывает заявки клиентов, предлагает условия")
Person(backOffice, "Сотрудник бэк-офиса", "Работает с данными по депозитам и кредитам")
Person(internetBankUser, "Пользователь интернет-банка", "Работает с депозитами через интернет-банк")
System(system, "Система открытия депозитов", "Обрабатывает заявки на депозиты и управляет ставками")
System(systemCS, "Система кол-центра", "Обрабатывает заявки от клиентов")
System(IB, "Интернет-банк", "Отображает список доступных депозитов для клиента")
System(ABS, "АБС банка", "Основная система для обработки банковских операций")
System_Ext(externalBank, "Центробанк", "Предоставляет ставки рефинансирования.")
System_Ext(externalСallCenterSystem, "Система партнёрского кол-центра", "Предоставляет услуги.")
System(site, "Сайт", "Отображает информацию")
Rel(internetBankUser, site, "Видит доступные депозиты и подает заявки через кол-центр")
Rel(callCenterManager, system, "Запрашивает условия")
Rel(callCenterManager, systemCS, "Обрабатывает заявки")
Rel(backOffice, system, "Работает с депозитами и согласует ставки")
Rel(internetBankUser, IB, "Видит персонализированные ставки и подает заявку через интернет-банк")

Rel(IB, ABS, "Отправляет заявки на открытие депозитов")
Rel(system, ABS, "Отправляет заявки на открытие депозитов")
Rel(ABS, ABS, "Читает и записывает ставки по депозитам")

Rel(system, callCenterManager, "Сообщает о статусе заявки")

@enduml