@startuml

!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Container.puml

LAYOUT_WITH_LEGEND()

Person(callCenterManager, "Менеджер кол-центра", "Обрабатывает заявки клиентов, предлагает условия")
Person(backOffice, "Сотрудник бэк-офиса", "Работает с данными по депозитам и кредитам")
Person(internetBankUser, "Пользователь интернет-банка", "Работает с депозитами через интернет-банк")

System_Boundary(internetBankSystem, "Интернет-банк",  "Интерфейс для пользователей интернет-банка") {
    Container(internetBankAPI, "API интернет-банка", "Java", "Обрабатывает запросы пользователей интернет-банка")
    Container(IBApp, "Интернет-банк", "React.js", "Веб-приложение", "Отображает список доступных депозитов клиентам.")
}

System_Boundary(ABSSystem, "АБС банка", "Основная система для обработки банковских операций") {
    Container(ABSApp, "АБС", "Серверное приложение", "Основная система для обработки банковских операций.")
    Container(databaseABS, "База данных АБС", "MS SQL / Oracle", "Сохраняет информацию о банковских операциях и ставках.")
}

System(systemDeposit, "Система открытия депозитов", "Java", "Обрабатывает заявки на депозиты и управляет ставками")
System(site, "Сайт", "Отображает информацию")
System(kafka, "Брокер для передачи данных", "kafka", "Передача данных в БД")
System(fileTransfer, "Система передачи файлов", "Java", "Передает актуальные ставки депозитов в виде файлов JSON")
System(systemCS, "Система кол-центра",  "Java", "Обрабатывает заявки от клиентов")
System_Ext(externalBank, "Центробанк", "Предоставляет ставки рефинансирования.")
System_Ext(externalСallCenterSystem, "Система партнёрского кол-центра", "Предоставляет услуги.")

Rel(internetBankUser, site, "Видит список депозитов и подает заявку")
Rel(callCenterManager, systemCS, "Обрабатывает заявки")

Rel(systemCS, systemDeposit, "Запрашивает условия и управляет ставками")
Rel(callCenterManager, systemCS, "Запрашивает условия и управляет ставками")

Rel(backOffice, systemDeposit, "Работает с депозитами и согласует ставки")
Rel(internetBankUser, IBApp, "Работает с депозитами через интернет-банк")
Rel(IBApp, internetBankAPI, "Отправляет заявки на открытие депозитов")
Rel(ABSApp, databaseABS, "Читает и записывает ставки по депозитам")
Rel(ABSApp, externalBank, "Запрашивает ставки рефинансирования")

Rel(internetBankAPI, kafka, "Отправляет запросы на открытие депозитов")
Rel(kafka, databaseABS, "Отправляет запросы на открытие депозитов")

Rel(systemDeposit, databaseABS, "Отправляет заявки на открытие депозитов")
Rel(systemCS, callCenterManager, "Сообщает о статусе заявки")
Rel(systemDeposit, systemCS, "Сообщает о статусе заявки")
Rel( fileTransfer, externalСallCenterSystem, "Получает актуальные ставки")
Rel(ABSApp, fileTransfer, "Передает актуальные ставки депозитов")

@enduml