@startuml
!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Component.puml

Person(client, "Клиент", "Подаёт заявку на открытие депозита только в отделении.")
Person(callCenterEmployee, "Сотрудник кол-центра", "Управляет обращениями клиентов.")
Person(branchEmployee, "Сотрудник отделения", "Обрабатывает заявки на место.")
Person(backOfficeEmployee, "Сотрудник бэк-офиса", "Обрабатывает заявки в АБС и определяет ставки.")
Person(creditDepartmentEmployee, "Сотрудник кредитования", "Анализирует уровень кредитного риска.")
System(ABS, "Автоматизированная банковская система", "Управляет данными о депозитах и кредитах.")
System(SMS, "СМС-шлюз телеком-оператора", "Отправляет СМС-уведомление.")
System(Site, "Сайт", "Маркетинговая информация.")
System(IB, "Интернет-банк", "Выполняет проведение платежей и открытие карт.")
Component(DB, "DB АБС", "Хранение данных.")
System(callCenterSystem, "Система колл-центра", "Обрабатывает первичное обращение клиента")
Component(excelFile, "Excel-файл", "Используется для расчёта на основе данных.")
System_Ext(externalBank, "Центробанк", "Предоставляет ставки рефинансирования.")
System_Ext(externalСallCenterSystem, "Система партнёрского кол-центра", "Предоставляет услуги.")

Rel(callCenterSystem, ABS, "Предварительная завявка от клиента")
Rel(DB, ABS, "Обмен данными")
Rel(DB, IB, "Обмен данными")
Rel(client, IB, "Выполнить платеж, открыть дебетовую карту")
Rel(client, branchEmployee, "Приходит в отделение впервые подавать заявку")
Rel(client, callCenterEmployee, "Звонит и уточняет детали открытия депозита")
Rel(callCenterEmployee, callCenterSystem, "Создаёт обращение, передаёт в АБС")
Rel(ABS, backOfficeEmployee, "Отправляет заявки для обработки")
Rel(backOfficeEmployee, excelFile, "Получает данные для расчёта ставок")
Rel(excelFile, creditDepartmentEmployee, "Запрашивает специальные ставки")
Rel(creditDepartmentEmployee, backOfficeEmployee, "Передает уровень риска")
Rel(creditDepartmentEmployee, ABS, "Анализирует уровень риска")
Rel(backOfficeEmployee, ABS, "Обрабатывает и определяет ставку клиента")
Rel(ABS, SMS, "Отправляет СМС-уведомление о ставке")
Rel(client, Site, "Получает маркетинговую информацию")
Rel(SMS, client, "Отправляет СМС-уведомление о ставке")
Rel(branchEmployee, client, "Информирует о ставке, обрабатывает заявление")
Rel(branchEmployee, backOfficeEmployee, "Запрашивает ставку, если клиент пришёл без звонка")
Rel(backOfficeEmployee, excelFile, "Принимает данные и делает расчёты")
Rel(branchEmployee, ABS, "Создаёт депозит и выдаёт документы")
Rel(branchEmployee, ABS, "Загружает подписанные документы")

@enduml